version: '3'
services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=testing
      - RABBITMQ_DEFAULT_PASS=123456

  api_gateway:
    build:
      context: ./api_gateway
    ports:
      - "5001:5001"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=queue_ofertas
      - RABBITMQ_USER=testing
      - RABBITMQ_PASS=123456
    depends_on:
      - rabbitmq